@startuml

Client -> Server : SYN
Client <- Server : SYN/ACK
Client -> Server : ACK
Client <--> Server : ESTABLISHED

Client -> Server : CLIENT HELLO
note left 
	- SSL Protocol version
	- SessionID
	- List of Cipher Suites
	- **CLIENT HELLO** Extensions
end note
Client <- Server : SERVER HELLO
note right
	- SSL Protocol version
	- Session ID
	- Selected Cipher
	- Server Certificate
	- **SERVER HELLO** Extensions
	- Client Certificate Request (Optional)
end note
Client -> Server : PRE MASTER SECRET
note left 
	- Pre-master secret
	- Client Cert (if requested)
end note
Client <--> Server : SESSION KEY CREATION
note right
	Server Authenticates the Client (Optional)
end note

... Master secret is used to generate Symmetric session keys ...

Client -> Server : CLIENT FINISHED
Client <- Server : SERVER FINISHED
Client <--> Server : EXCHANGE MESSAGES


@enduml
